# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from tools.botrpc import console_pb2 as tools_dot_botrpc_dot_console__pb2


class BotStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.toBot = channel.unary_unary(
        '/console.Bot/toBot',
        request_serializer=tools_dot_botrpc_dot_console__pb2.request.SerializeToString,
        response_deserializer=tools_dot_botrpc_dot_console__pb2.response.FromString,
        )


class BotServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def toBot(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BotServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'toBot': grpc.unary_unary_rpc_method_handler(
          servicer.toBot,
          request_deserializer=tools_dot_botrpc_dot_console__pb2.request.FromString,
          response_serializer=tools_dot_botrpc_dot_console__pb2.response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'console.Bot', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
