# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tools/botrpc/console.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tools/botrpc/console.proto',
  package='console',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1atools/botrpc/console.proto\x12\x07\x63onsole\"\x17\n\x07request\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x18\n\x08response\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t25\n\x03\x42ot\x12.\n\x05toBot\x12\x10.console.request\x1a\x11.console.response\"\x00\x62\x06proto3')
)




_REQUEST = _descriptor.Descriptor(
  name='request',
  full_name='console.request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='console.request.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=62,
)


_RESPONSE = _descriptor.Descriptor(
  name='response',
  full_name='console.response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='console.response.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=88,
)

DESCRIPTOR.message_types_by_name['request'] = _REQUEST
DESCRIPTOR.message_types_by_name['response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

request = _reflection.GeneratedProtocolMessageType('request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'tools.botrpc.console_pb2'
  # @@protoc_insertion_point(class_scope:console.request)
  })
_sym_db.RegisterMessage(request)

response = _reflection.GeneratedProtocolMessageType('response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'tools.botrpc.console_pb2'
  # @@protoc_insertion_point(class_scope:console.response)
  })
_sym_db.RegisterMessage(response)



_BOT = _descriptor.ServiceDescriptor(
  name='Bot',
  full_name='console.Bot',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=90,
  serialized_end=143,
  methods=[
  _descriptor.MethodDescriptor(
    name='toBot',
    full_name='console.Bot.toBot',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BOT)

DESCRIPTOR.services_by_name['Bot'] = _BOT

# @@protoc_insertion_point(module_scope)
